#!/bin/sh

PROGRAM=setup-networking-with-wifi-only
VERSION=exported

# PREFIX=
# . $PREFIX/lib/libalpine.sh
# . $PREFIX/lib/libusralpine.sh

INTERFACESDIR=/etc/network
INTERFACES=interfaces
WPASUPPLICANTCNFDIR=/etc/wpa_supplicant
WPASUPPLICANTCNF=wpa_supplicant.conf

cat >$INTERFACESDIR/$INTERFACES <<-__EOF__
# alpine-user-conf: setup-networking-with-wifi
auto lo
iface lo inet loopback

auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
__EOF__

echo "Add wpa_supplicant"
apk add wpa_supplicant

cat >$WPASUPPLICANTCNFDIR/$WPASUPPLICANTCNF <<-__EOF__
# alpine-user-conf: setup-networking-with-wifi
ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=wheel
ap_scan=1
autoscan=period:10
disable_scan_offload=1
update_config=1
__EOF__

rc-update add wpa_supplicant boot
rc-update add networking boot
rc-update add wpa_cli boot

/etc/init.d/networking restart
