#!/bin/sh

if [ "$(id -u)" -ne 0 ] || [ "$TARGET_USER" = "root" ] || [ "$TARGET_USER" = "" ]; then
   echo "run this script as root and set TARGET_USER environment variable"
   exit 1
fi

#########################################################################################
# PROGRAM METADATA
#########################################################################################

PROGRAM=$(basename "$0")

#########################################################################################
# PROGRAM DEPENDENCIES
#########################################################################################

. "/lib/libusralpine.sh"

#########################################################################################
# PROGRAM 
#########################################################################################

step "adding doas"
apk add doas

step "adding root to wheel group"
addgroup root wheel

step "adding $TARGET_USER to wheel group"
addgroup "$TARGET_USER" wheel

step "adding configuration"
cat >/etc/doas.conf <<-__EOF__
# alpine-user-conf: setup-doas

# This file is actually located at /etc/doas.d/doas.conf, and reflects
# the system doas configuration.  It may have been migrated from its
# previous location, /etc/doas.conf, automatically.

permit persist :wheel
__EOF__