#!/bin/sh

if [ "$(id -u)" -ne 0 ] || [ "$DOAS_USER" = "root" ] || [ "$DOAS_USER" = "" ]; then
   echo "run this script as a regular user using doas"
   exit 1
fi

#########################################################################################
# PROGRAM METADATA
#########################################################################################

PROGRAM=$(basename "$0")

#########################################################################################
# PROGRAM DEPENDENCIES
#########################################################################################

. "/lib/libusralpine.sh"

#########################################################################################
# PROGRAM 
#########################################################################################

header "$PROGRAM"


step "adding dbus"
apk add dbus dbus-openrc || die "dbus setup - failed to install dbus"

step "adding dbus service to default"
rc-update add dbus default || die "dbus setup - failed to add dbus service to default"

step "starting dbus service"
rc-service dbus start || die "dbus setup - failed to start dbus service"