#!/bin/sh

PROGRAM=setup-networking-with-wifi-only
VERSION=0.1

echo "Adding wpa_supplicant"
apk add wpa_supplicant

echo "Overwriting /etc/network/interfaces with custom configuration"
cat >/etc/network/interfaces <<-__EOF__
# alpine-user-conf: setup-networking-with-wifi-only
auto lo
iface lo inet loopback

auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
__EOF__


echo "Overwriting /etc/wpa_supplicant/wpa_supplicant.conf with custom configuration"
cat >/etc/wpa_supplicant/wpa_supplicant.conf <<-__EOF__
# alpine-user-conf: setup-networking-with-wifi-only
ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=wheel
ap_scan=1
autoscan=period:3
disable_scan_offload=1
update_config=1
__EOF__

echo "Adding networking service to boot"
rc-update add networking boot

echo "Adding wpa_supplicant service to boot"
rc-update add wpa_supplicant boot

echo "Adding wpa_cli service to boot"
rc-update add wpa_cli boot

echo "Starting/Restarting wpa_suppliant service"
rc-service wpa_supplicant restart

echo "Starting/Restarting wpa_cli service"
rc-service wpa_cli restart

echo "Starting/Restarting networking service"
rc-service networking restart
